import React from 'react'
import Header from './Header'
import Footer from './Footer'

function MentalArticle() {
    return (
        <>
            <Header />
            <div style={{ padding: "20px" }}>
                <h1 className='text-3xl font-bold text-center my-5 sm:text-5xl'>HOW TO CURE MENTAL ILLNESS?</h1>
                
                <div className='flex flex-col-reverse md:flex-row'>
                    <p className='my-5 md:w-2/3'>
                        The nature of mental illness has been the subject of passionate discussion throughout history. In ancient Greece Plato,1,2 promoting a mentalist definition of mental illness, was the first to coin the term “mental health,” which was conceived as reason aided by temper and ruling over passion. At around the same time, Hippocrates,3 taking a more physicalist approach, defined different mental conditions as a variety of imbalances between different kinds of “humours.” Griesinger4,5 almost 2 centuries ago was the first to state that “mental illness is brain illness,” an expression that has provided a strong impetus to the more recent medical conception of mental illness. The substantial progress accomplished in genomics and brain imaging in the last few decades made biological psychiatry stronger than ever and contributed to the reification of mental disorders as illnesses of the brain. The almost exclusively biogenetic conceptual framework for understanding mental illness has acquired a hegemony that has influenced mental health practitioners while also influencing campaigns designed to improve public attitudes toward the mentally ill. As a result, the statement “mental illness is like any other illness” has become almost axiomatic and, therefore, by definition it embodies an accepted truth not in need of a proof.
                    </p>
                    <img src="\images\c_1.jpg" alt="" className='w-full md:w-1/3 h-56' />
                </div>

                <p className='my-5'>
                    This view of mental illness is presented for better acceptance of the mentally ill by the public and of treatment by those experiencing mental illness and is indeed based on accumulated, albeit limited, knowledge in the neurobiology of mental disorders. However, anything that reaches axiomatic proportions needs a serious examination. In this editorial we examine the reasons underlying this perspective, its consequences and the evidence to support or refute its continued justification. We then present a position that we believe best fits the current state of knowledge and is closest to clinical realities and public perceptions of mental illnesses.
                </p>
                <h2 className='text-3xl font-bold'>What does the statement actually imply?</h2>
                <p className='my-5'>
                    The statement that “mental illness is like any other medical illness” implies that mental illness has a biological basis just like other medical illnesses and should be treated in the public’s eye in a similar manner. The purpose of this article is not to present a philosophical or ideological argument in favour of or against a biological basis explaining mental illness, but rather to examine the clinical and public utility of presenting a dominant neurobiological model of mental illness to patients, their families and the public at large.
                </p>
                <h2 className='text-3xl font-bold'>Neurobiology and experience of mental illness</h2>
                <p className='my-5'>Advances in neurosciences have surely given us much better biological mechanistic explanations of many of the uniquely human cognitive, emotional and conative functions, such as memory, thinking, perception, mood and action. This knowledge has informed us that many mental illnesses derive their vulnerability from underlying biological variations. However, we are far from being able to explain in neurobiological terms many of the behaviours and experiences that constitute the core presentations of mental disorders. Even if neurobiology one day were to provide better explanations of the workings of the brain, more elaborately explain the role of genes in increasing the risk for mental illness and the mechanisms behind complex human behaviour, one would still need to understand the experiences of patients with different forms of mental illness in psychological terms, as recently described by Kendler9 so eloquently. By equating mental illness with any medical illness and, therefore, situating it in an organ within the human biology and not recognizing its unique nature in the way it affects the “self” cannot be justified on the basis of current state of knowledge nor may it serve our patients and society well, as we explain in the rest of this editorial.</p>
                <h2 className='text-3xl font-bold'>Mental illness and the utility of explanatory models</h2>
                <p className='my-5'>Indeed, it is envisaged that putting mental illness on the same footing as medical illness, society will understand it better and not react negatively toward those with mental illnesses. It is hoped that as a result those with mental illness may face less social stigma — a major obstacle to people seeking and/or receiving help — and reducing stigma may help individuals regain eventual acceptance by society as productive members. Interestingly, the public’s explanatory models of mental illness do not follow this narrative and, on the contrary, the public have multiple models of explaining mental illness varying across cultures and times.

                    One needs to ask the pragmatic question of whether the strategy of using a biogenetic model of mental illness and equating it with medical illness has actually helped. There are 2 areas worthy of examination in this regard.</p>
                <h2 className='text-3xl font-bold'>What needs to be done?</h2>
                <p className='my-5'>In clinical practice, if we are to take seriously the multidimensional goals of providing mental health services, as articulated by those seeking and receiving help for mental illness, clinicians have to work within an attributional model that makes sense to the person receiving service, that can be supported by sound argument and evidence and that provides a framework within which those receiving service and those providing it can share a common language. Such a framework will need to include the biogenetic model of attribution of mental illness as 1 of several parallel and equally authentic social, psychological, environmental and cultural models offered by service providers and researchers (acquired knowledge) as well as those who experience mental illness (experiential knowledge). There is a need to create a common language in order to come to an understanding of the person’s experience and to promote such an understanding among the public at large. Denying the special nature of mental illness is unlikely to achieve these important goals.
                    Some recent developments, such as the promotion of a recovery model21–23 and the early intervention movement,24,25 may hold more promise in improving both the quality of care and possibly involvement of and improvement in public attitudes. The former has emerged from experiential knowledge and advocacy from service users, supported later by sound qualitative research, whereas the latter has emerged from a combination of a shift in philosophy of delivery of care on the part of service providers, parallel generation of evidence of its effectiveness26,27 and greater acceptance by service users and their families, who have now joined the movement as advocates. A third emerging movement, the concept of positive mental health,28,29 may prove to be effective in combating the negative image of mental illness. This movement promotes and is based on human resilience and positive aspects of the experience of mental illness. There is a burgeoning literature emerging in this field, which may balance the rather deterministic, deficit oriented and largely pessimistic miasma created by using an exclusively biogenetic model to explain mental disorders.
                </p>
                <h2 className='text-3xl font-bold'>Conclusion and recommendations</h2>
                <p className='my-5'>Simply seeking an axiom of “mental illness is like any other medical illness” is at best simplifying a complex human problem and at worst doing a major disservice to patients, their families and the mental health field. Our dialogue should incorporate the general complexity of human thinking, behaviour, memories and the idea of self and consciousness, including knowledge emerging from sophisticated biogenetic and social science research while attending to the specific complexities that each of us as human beings carry as part of our life stories. That is true for those receiving and those providing services.

                    We therefore argue that we should continue to have a social and a professional conversation where we find a proper place for neurobiology, social, cultural and environmental forces, personal histories and the uniqueness of each individual when trying to understand, explain and treat mental disorders while avoiding a simplistic reductionism that may be perceived at best as patronizing but ultimately harmful, even though the intentions may be noble. We propose that future antistigma campaigns should give up the axiom of “mental illness is like any other medical illness” and instead present the complex and multifaceted explanations of mental illness as unique along with the positive aspects as discussed here. These campaigns need to be informed not only by the acquired knowledge of service providers and scientists but equally by the experiential knowledge from service users and their families, taking into consideration new knowledge emerging from fields of recovery, early intervention and positive mental health. For clinicians, it would be equally important to embrace explanatory models of mental illness that are based on evidence in science and to include biogenetic, social and cultural models as well as those told to them by the very people they are trying to serve.</p>
            </div>
            <Footer />
        </>
    )
}

export default MentalArticle
