import React from 'react'
import Header from './Header'
import Footer from './Footer'

function TobaccoArticle() {
    return (
        <>
            <Header />
            <div style={{ padding: "20px" }}>
                <h1 className='text-3xl font-bold text-center my-5 sm:text-5xl'>Empowering Communities: Uniting for a Tobacco-Free Future</h1>

                <div className='flex flex-col-reverse md:flex-row'>
                    <p className='my-5 md:w-2/3'>
                        Tobacco use kills nearly six million people worldwide each year. According to the World Health Organization (WHO) estimates, globally, there were 100 million premature deaths due to tobacco in the 20th century, and if the current trends of tobacco use continue, this number is expected to rise to 1 billion in the 21st century.

                        Jha et al. have estimated that around 1 million deaths a year in India will be attributable to smoking by the early 2010s. Gupta et al. have estimated the tobacco-attributable mortality among Indian men and women from their Mumbai cohort study. Based on these estimates, nearly 23.7% of the deaths among men (527,500) and 5.7% of the deaths among women (83,000) aged 35–69 years are due to tobacco-attributable illnesses. Another cohort study from southern India reported mortality risks of 0.98 (0.86–0.94) and 1.22 (1.04–1.44) for all-cause and tobacco-related cancer mortality, respectively, for tobacco chewing, while with smoking, the respective mortality risks were 1.31 (1.24–1.39) and 1.68 (1.36–2.08).

                        According to the National Family Health Survey (NFHS)-3 survey, conducted in 2005–06, tobacco use is more prevalent among men, rural population, illiterates, poor and vulnerable section of the society. The estimates of the Global Adult Tobacco Survey (GATS) conducted among persons 15 years of age or older during 2009–10 indicate that 34.6% of the adults (47.9% males and 20.3% females) are current tobacco users. Fourteen percent of the adults smoke (24.3% males and 2.9% females) and 25.9% use smokeless tobacco (32.9% males and 18.4% females). According to the Global Youth Tobacco Survey (GYTS) conducted among 24,000 students aged 13–15 years in 2009, 14.6% students were tobacco users.

                        India's tobacco problem is very complex, with a large use of a variety of smoking forms and an array of smokeless tobacco products. Many of these products are manufactured as cottage and small-scale industries using varying mixtures and widely differing processes of manufacturing. Bidis are mostly manufactured in the unorganized sector while cigarettes are mainly manufactured in large-scale industries.
                    </p>
                    <img src="\images\tobacco_article.avif" alt="" className='w-full md:w-1/3 h-80' />
                </div>

                <p className='mb-5'>
                    This view of mental illness is presented for better acceptance of the mentally ill by the public and of treatment by those experiencing mental illness and is indeed based on accumulated, albeit limited, knowledge in the neurobiology of mental disorders. However, anything that reaches axiomatic proportions needs a serious examination. In this editorial we examine the reasons underlying this perspective, its consequences and the evidence to support or refute its continued justification. We then present a position that we believe best fits the current state of knowledge and is closest to clinical realities and public perceptions of mental illnesses.
                </p>
                <h2 className='text-3xl font-bold'>HAZARDS OF TOBACCO USE :</h2>
                <h3 className='text-2xl font-semibold my-2'>Health</h3>
                <p className='my-5'>
                    Tobacco is deadly in any form or disguise. Scientific evidence has unequivocally established that exposure to tobacco smoke causes death, disease and disability. According to the International Agency for Research on Cancer (IARC) monograph, there is sufficient evidence in humans that tobacco smoking causes cancer of the lung, oral cavity, naso-, oro- and hypo-pharynx, nasal cavity and paranasal sinuses, larynx, esophagus, stomach, pancreas, liver, kidney (body and pelvis), ureter, urinary bladder, uterine cervix and bone marrow (myeloid leukemia). Colorectal cancer is seen to be associated with cigarette smoking, although there is insufficient evidence for it to be causal. Ninety percent of all lung cancer deaths in men and 80% in women are caused by smoking. Causal associations have been clearly established between active smoking and adverse reproductive outcomes, chronic obstructive pulmonary disease and cardiovascular diseases. Studies on bidi smoking, the most common form of tobacco smoking in India, provide evidence toward causality of it as carcinogenic substance. Case–control studies demonstrate a strong association of bidi smoking with cancers at various sites, such as oral cavity (including subsites), pharynx, larynx, esophagus, lung and stomach. Almost all studies show significant trends with duration of bidi smoking and number of bidis smoked. Forty percent of the tuberculosis burden in India may be attributed to smoking. Significant association is seen between passive or active exposure to tobacco smoke and tuberculous infection, disease and tuberculosis mortality. Smoking was associated with excess deaths among smokers between 30 and 69 years, mainly from tuberculosis and also from respiratory, vascular or neoplastic disease. The risk of tuberculosis deaths among bidi smokers was 2.60-times higher than never-smokers in Mumbai. Workers engaged in tobacco cultivation suffer from an occupational illness known as green tobacco sickness (GTS), an acute form of nicotine toxicity resulting from absorption of nicotine through the skin.
                </p>
                <h3 className='text-2xl font-semibold'>Passive smoking</h3>
                <p className='my-5'>Second-hand tobacco smoke (SHS) kills 600,000 people each year. Globally, about one-third adults are regularly exposed to SHS. The GATS-India shows that 52% of the adults (rural-58%, urban-39%) were exposed to SHS at home. SHS is three- to four-times more toxic per gram of particulate matter than mainstream tobacco smoke. More than 4000 chemicals have been identified in tobacco smoke, at least 250 of which are known to be harmful. Toxic chemicals from SHS cling to rugs, curtains, clothes, food, furniture and other materials. These toxins remain even in the presence of windows, fans or air filters, and can recycle back into the air through the filters. They coat the surfaces of rooms, materials and smoker's belongings, and are sometimes referred to as “third-hand smoke.” There is conclusive evidence linking passive smoking to an increased risk of cardiovascular diseases, lung cancer and other cancers, asthma and other respiratory diseases in adults and asthma and other respiratory diseases, ear infection and sudden infant death syndrome in children, to name but a few of passive smoking's harmful effects.</p>

                <h2 className='text-3xl font-bold'>LEGISLATION AND ENFORCEMENT</h2>
                <h3 className='text-2xl my-2 font-semibold'>WHO framework convention on tobacco control</h3>
                <p className='my-5'>Legislation is recognized as the critical driver for meaningful progress in tobacco control. The WHO framework convention on tobacco control (WHO FCTC) is a global public health treaty developed as a global response to the globalization of the tobacco epidemic, which aims at reducing the burden of disease and death caused by tobacco. It was adopted by the World Health Assembly in May 2003, and India was the eighth country to ratify it on 5 February 2004. The FCTC embraces scientific evidence-based approaches that have shown effectiveness in reducing tobacco consumption. It does not lay down a law, but sets out guidelines for various national and international measures that would encourage smokers to quit and restrain nonsmokers from taking the habit. The success of the WHO FCTC, which as of July 2009 had more than 160 parties covering 86% of the world's population, demonstrates the global political will for making tobacco control far more comprehensive and successful. The WHO has established the MPOWER package to help countries comply with the WHO FCTC. This is a package encompassing six most important and effective tobacco control policies: Monitoring tobacco use and prevention policies, Protecting people from tobacco smoke, Offering help to people to quit tobacco use, Warning everyone about the dangers of tobacco, Enforcing ban on tobacco advertising, promotion and sponsorship and Raising taxes on tobacco.
                    In India, since 1975, it is mandatory to display a statutory health warning on all packages and advertisements of cigarettes because of the Cigarettes (Regulation of Production, Supply and Distribution) Act, enacted by the Government of India (GOI). Further restrictions on tobacco trade were initiated along with efforts to bring forth a comprehensive legislation for tobacco control during the 1980s and 1990s. The Indian Parliament passed the Cigarettes and Other Tobacco Products (Prohibition of Advertisement and Regulation of Trade and Commerce, Production, Supply and Distribution) Bill, 2003 in April 2003. This Bill became an Act on 18 May 2003 – COTPA. Rules were formulated and enforced from 1 May 2004. The Act is applicable to all products containing tobacco in any form, and extends to the whole of India.</p>
                <p>The key provisions of COTPA -2003 are as follows :</p>
                <ul className='list-decimal'>
                    <li>Prohibition of smoking in public places (including indoor workplaces). This has been implemented from 2nd October 2008 in the whole of India.</li>
                    <li>Prohibition of advertisement, direct and indirect (point-of-sale advertising is permitted), sponsorship and promotion of tobacco products.</li>
                    <li>Prohibition of sales to minors (tobacco products cannot be sold to children less than 18 years of age and cannot be sold within a radius of 100 yards of any educational institutions).</li>
                    <li>Regulation of health warning in tobacco products packs. English and one more Indian language to be used for health warnings on tobacco packs. Pictorial health warnings also to be included.</li>
                    <li>Regulation and testing of tar and nicotine contents of tobacco products and declaring on tobacco products packages.</li>
                </ul>
                <h3 className='text-2xl font-semibold mt-5'>National tobacco control programme</h3>
                <p className='mb-5'>The Ministry of Health and Family Welfare (MHFW), GOI, has launched the National tobacco control programme (NTCP) in the XI Five Year Plan to facilitate the implementation of the Tobacco Control Laws, bring about greater awareness about the harmful effects of tobacco and to fulfill the obligations under the WHO-FCTC. The Cabinet Committee on Economic Affairs (CCEA) on 28 January 2010 approved the programme. The NTCP will establish tobacco product testing laboratories, provide baseline estimates of tobacco prevalence and status of implementation of the Tobacco Control Law. The pilot phase will focus on 42 districts of 21 states. The activities of NTCP are arranging exhibitions, seminars, banners at District level, implementing the anti-tobacco act in letter and spirit, sending monthly reports regarding the anti-tobacco activities in the district level to the state. At the headquarters the activities focused are promoting Information, Education and Communication (IEC) activities at the district level and multi-sectoral involvement for the implementation of the Act with the help of NGOs, Police Department, Education Department and the Local Administration.

                    Numerous voluntary organizations like the HRIDAY-SHAN, CPAA-Cancer patients aids association, the Salaam Mumbai Foundation, HealthBridge, Voluntary Health Association of India, etc. are actively involved in tobacco control activities in India. Healis is actively engaged in conducting quality research in tobacco control. In addition, it is involved in media mobilization for tobacco control, public education, conducting workshops for different stake holders and conducting scientific conferences and meetings of national and international level. The Public Health Foundation of India (PHFI) has launched a multi-faceted website to create an enabling environment for tobacco control in the country. The web portal comprehensively offers training, resources and research evidence with regard to tobacco control. To support global efforts for tobacco control, The Union focuses on several key policies that are proven to reduce tobacco consumption. In India, the Union has been active in collaborating with the central and state governments and prominent NGOs to strengthen pack warning content and its implementation. The WHO is actively involved in tobacco control in India. Tobacco surveillance has been included in the integrated disease surveillance programme. A National Tobacco Control Cell was set up by the WHO in collaboration with the Ministry of Health and Family Welfare, which has activities in the different spheres of tobacco control, with the main impetus on spreading awareness.</p>
                <h2 className='text-3xl font-bold'>WHAT WORKS FOR TOBACCO CONTROL?</h2>
                <p className='my-5'>There is strong evidence that tobacco tax increases, the dissemination of information about the health risks from tobacco and increased access to cessation therapies are effective in reducing tobacco use. However, their implementation is uneven and limited, with higher-income countries having more anti-smoking laws in place than the low- and middle-income countries. Effective implementation may be affected by the tobacco industry lobbying power, partly due to political constraints and the country's overall commitment to tobacco control. The International Tobacco Control Policy Evaluation Project (ITC Project) designed to evaluate the impact of policies implemented under WHO FCTC will provide further evidence base to guide policies enacted under the FCTC and systematically evaluate the effectiveness of these legislative efforts.
                </p>
                <h2 className='text-3xl font-bold'>THE WAY AHEAD</h2>
                <p className='my-5'>Measures that proved very effective in the developed world, like tax increases on all tobacco products, need to be enforced immediately and the taxes collected should be used to support health promotion and tobacco control programmes. Sustained efforts are needed from the Government to strengthen efforts on alternate cropping and alternate livelihoods to replace employment losses that may come up gradually.
                    Public health awareness, raising a mass movement against tobacco, sensitizing and educating all health care professionals for tobacco control and cessation by incorporating the topic in medical undergraduate curriculum, nursing curriculum, various CMEs, conferences, scientific meetings, workshops, etc. is vital. Eventually, if all healthcare professionals participate in tobacco control and cessation, it will have a huge impact. Expansion of TCCs to the periphery to reach the community, making them more accessible and widely acceptable, will facilitate millions of current tobacco users to quit the habit.</p>
            </div>
            <Footer />
        </>
    )
}

export default TobaccoArticle
